name: Build next app

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop

jobs:
  teste-frontend:
    name: Teste de Front
    runs-on: ubuntu-latest

    steps:
      - name: Verificação do código
        uses: actions/checkout@v3

      - name: Configuração do Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalação do pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false

      - name: Obter cache do pnpm
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Instalando pacotes do Frontend
        working-directory: .
        run: pnpm install

      - name: Configurar ambiente para CI
        working-directory: .
        run: cp .env.example .env

      - name: Executando testes de Build do Front
        working-directory: .
        run: pnpm run build

  build-docker:
    name: Build e teste das imagens
    runs-on: ubuntu-latest
    needs:
      - teste-frontend
    steps:
      - name: Verificando Código
        uses: actions/checkout@v3

      - name: Criando imagem do Frontend
        run: docker build -t frontend-app .
